import os
from facebook_business.api import FacebookAdsApi
from facebook_business.adobjects.adaccount import AdAccount
from facebook_business.adobjects.adset import AdSet

def apply_cmo_decisions(commands: list, dry_run: bool = True):
    """
    Takes the JSON decisions generated by Gemini and executes them against the Meta Ads API.
    Args:
        commands (list[AdCommand]): The Pydantic parsed list of actions.
        dry_run (bool): If True, only prints the intended actions rather than dispatching them.
    """
    app_id = os.environ.get("META_APP_ID")
    app_secret = os.environ.get("META_APP_SECRET")
    access_token = os.environ.get("META_ACCESS_TOKEN")
    
    if not all([app_id, app_secret, access_token]):
        print("Warning: Missing Meta API credentials. Running in simulated dry-run mode only.")
        dry_run = True
    else:
        FacebookAdsApi.init(app_id, app_secret, access_token)
        
    print(f"--- Meta Executor (Dry Run: {dry_run}) ---")
    
    for cmd in commands:
        action = cmd.action
        adset_id = cmd.adset_id
        reasoning = cmd.reasoning
        
        print(f"Processing Action: {action} for AdSet: {adset_id}")
        print(f"  Reasoning: {reasoning}")
        
        if dry_run:
            print(f"  [DRY RUN] Would change status of {adset_id} to {action}.")
            continue
            
        try:
            adset = AdSet(adset_id)
            
            if action == "PAUSE":
                adset.update({AdSet.Field.status: AdSet.Status.paused})
                print(f"  [SUCCESS] Paused AdSet {adset_id}.")
                
            elif action == "SCALE_UP":
                # In order to scale up, we first need to read the current budget
                # Note: Not all AdSets have daily_budget, some have lifetime_budget.
                fields = ['daily_budget']
                adset_state = adset.api_get(fields=fields)
                
                current_budget = float(adset_state.get('daily_budget', 0))
                
                if current_budget > 0:
                    scale_factor = 1.0 + (cmd.percentage / 100.0)
                    new_budget = int(current_budget * scale_factor)
                    adset.update({AdSet.Field.daily_budget: new_budget})
                    print(f"  [SUCCESS] Scaled {adset_id} daily budget from {current_budget} to {new_budget}.")
                else:
                    print(f"  [SKIPPED] Cannot scale: AdSet uses Lifetime Budget or is invalid.")
                    
            elif action == "SCALE_DOWN":
                fields = ['daily_budget']
                adset_state = adset.api_get(fields=fields)
                current_budget = float(adset_state.get('daily_budget', 0))
                
                if current_budget > 0:
                    scale_factor = 1.0 - (cmd.percentage / 100.0)
                    new_budget = int(current_budget * scale_factor)
                    adset.update({AdSet.Field.daily_budget: new_budget})
                    print(f"  [SUCCESS] Scaled down {adset_id} daily budget from {current_budget} to {new_budget}.")
                    
            elif action == "NO_ACTION":
                print("  [SKIPPED] No action required.")
                
        except Exception as e:
            print(f"  [ERROR] Failed to execute {action} for AdSet {adset_id}: {e}")
